version: "3.8"

services:
  manager:
    image: 'ghcr.io/flux-agi/flux-env-manager:latest'
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - app
    environment:
      - MANAGER__DOCKER__LOGIN=${MANAGER__DOCKER__LOGIN}
      - MANAGER__DOCKER__PASSWORD=${MANAGER__DOCKER__PASSWORD}

  loki:
    image: grafana/loki:2.4.1
    restart: unless-stopped
    ports:
      - "3100:3100"
    networks:
      - app

  nats:
    image: 'nats:alpine3.20'
    restart: unless-stopped
    expose:
      - "4222"
    ports:
      - "4222:4222"
      - "8222:8222"
    environment:
      - NATS_MONITOR_PORT=8222
    hostname: nats-server
    networks:
      - app
      
networks:
  app:
    name: "flux-network"
    attachable: true
